// 90 IPIP Big Five personality questions
// Domains: E = Extraversion, A = Agreeableness, C = Conscientiousness,
//          N = Neuroticism, O = Openness to Experience (18 each)
// Scale:   1 = Very Inaccurate … 5 = Very Accurate

const LIKERT_OPTIONS = [
  "Very Inaccurate",
  "Moderately Inaccurate",
  "Neither Accurate Nor Inaccurate",
  "Moderately Accurate",
  "Very Accurate",
];

const questions = [
  // ── Extraversion ──────────────────────────────────────────────────────────
  { question: "I am the life of the party.",                                      domain: "E", options: LIKERT_OPTIONS },
  { question: "I feel comfortable around people.",                                domain: "E", options: LIKERT_OPTIONS },
  { question: "I start conversations easily.",                                    domain: "E", options: LIKERT_OPTIONS },
  { question: "I talk to a lot of different people at social gatherings.",        domain: "E", options: LIKERT_OPTIONS },
  { question: "I don't mind being the center of attention.",                      domain: "E", options: LIKERT_OPTIONS },
  { question: "I am skilled in handling social situations.",                      domain: "E", options: LIKERT_OPTIONS },
  { question: "I make friends easily.",                                           domain: "E", options: LIKERT_OPTIONS },
  { question: "I have a lot to say in conversations.",                            domain: "E", options: LIKERT_OPTIONS },
  { question: "I take charge when working in groups.",                            domain: "E", options: LIKERT_OPTIONS },
  { question: "I feel energized after spending time with people.",                domain: "E", options: LIKERT_OPTIONS },
  { question: "I prefer to stay in the background.",                              domain: "E", options: LIKERT_OPTIONS },
  { question: "I find it hard to approach others.",                               domain: "E", options: LIKERT_OPTIONS },
  { question: "I would rather stay home than go out to a social event.",          domain: "E", options: LIKERT_OPTIONS },
  { question: "I have little to say in group settings.",                          domain: "E", options: LIKERT_OPTIONS },
  { question: "I keep to myself most of the time.",                               domain: "E", options: LIKERT_OPTIONS },
  { question: "I don't like drawing attention to myself.",                        domain: "E", options: LIKERT_OPTIONS },
  { question: "I enjoy meeting new and different people.",                        domain: "E", options: LIKERT_OPTIONS },
  { question: "I enjoy going on adventures with others.",                         domain: "E", options: LIKERT_OPTIONS },

  // ── Agreeableness ─────────────────────────────────────────────────────────
  { question: "I am interested in other people's feelings and problems.",         domain: "A", options: LIKERT_OPTIONS },
  { question: "I take time out for others.",                                      domain: "A", options: LIKERT_OPTIONS },
  { question: "I make people feel at ease.",                                      domain: "A", options: LIKERT_OPTIONS },
  { question: "I love helping others.",                                           domain: "A", options: LIKERT_OPTIONS },
  { question: "I am always willing to listen to people's problems.",              domain: "A", options: LIKERT_OPTIONS },
  { question: "I feel concern for others who are less fortunate.",                domain: "A", options: LIKERT_OPTIONS },
  { question: "I try to understand people's points of view.",                     domain: "A", options: LIKERT_OPTIONS },
  { question: "I am good at cooperating with others.",                            domain: "A", options: LIKERT_OPTIONS },
  { question: "I trust what people say.",                                         domain: "A", options: LIKERT_OPTIONS },
  { question: "I believe in working things out peacefully.",                      domain: "A", options: LIKERT_OPTIONS },
  { question: "I think mostly of myself.",                                        domain: "A", options: LIKERT_OPTIONS },
  { question: "I am not really interested in others' problems.",                  domain: "A", options: LIKERT_OPTIONS },
  { question: "I tend to find fault with others.",                                domain: "A", options: LIKERT_OPTIONS },
  { question: "I am not sympathetic to people's feelings.",                       domain: "A", options: LIKERT_OPTIONS },
  { question: "I hold a grudge for a long time.",                                 domain: "A", options: LIKERT_OPTIONS },
  { question: "I contradict others frequently.",                                  domain: "A", options: LIKERT_OPTIONS },
  { question: "I find it easy to resolve conflicts with others.",                 domain: "A", options: LIKERT_OPTIONS },
  { question: "I value cooperation over competition.",                            domain: "A", options: LIKERT_OPTIONS },

  // ── Conscientiousness ─────────────────────────────────────────────────────
  { question: "I am always prepared before starting a task.",                     domain: "C", options: LIKERT_OPTIONS },
  { question: "I pay close attention to details.",                                domain: "C", options: LIKERT_OPTIONS },
  { question: "I follow a schedule and stick to it.",                             domain: "C", options: LIKERT_OPTIONS },
  { question: "I get tasks done right away.",                                     domain: "C", options: LIKERT_OPTIONS },
  { question: "I like having things organized.",                                  domain: "C", options: LIKERT_OPTIONS },
  { question: "I make plans and stick to them.",                                  domain: "C", options: LIKERT_OPTIONS },
  { question: "I complete tasks on time.",                                        domain: "C", options: LIKERT_OPTIONS },
  { question: "I set high standards for myself and work hard to meet them.",      domain: "C", options: LIKERT_OPTIONS },
  { question: "I work hard and take my responsibilities seriously.",              domain: "C", options: LIKERT_OPTIONS },
  { question: "I set goals and work steadily toward them.",                       domain: "C", options: LIKERT_OPTIONS },
  { question: "I often forget to put things back in their proper place.",         domain: "C", options: LIKERT_OPTIONS },
  { question: "I leave a mess wherever I go.",                                    domain: "C", options: LIKERT_OPTIONS },
  { question: "I have difficulty starting tasks.",                                domain: "C", options: LIKERT_OPTIONS },
  { question: "I leave jobs half-finished.",                                      domain: "C", options: LIKERT_OPTIONS },
  { question: "I find it hard to keep my focus on one thing for long.",           domain: "C", options: LIKERT_OPTIONS },
  { question: "I avoid my responsibilities whenever possible.",                   domain: "C", options: LIKERT_OPTIONS },
  { question: "I am careful to double-check my work.",                            domain: "C", options: LIKERT_OPTIONS },
  { question: "I like to organize activities before starting them.",              domain: "C", options: LIKERT_OPTIONS },

  // ── Neuroticism ───────────────────────────────────────────────────────────
  { question: "I get stressed out easily.",                                       domain: "N", options: LIKERT_OPTIONS },
  { question: "I worry about things a lot.",                                      domain: "N", options: LIKERT_OPTIONS },
  { question: "I often fear that the worst will happen.",                         domain: "N", options: LIKERT_OPTIONS },
  { question: "I often feel down or in low spirits.",                             domain: "N", options: LIKERT_OPTIONS },
  { question: "I am easily disturbed by things around me.",                       domain: "N", options: LIKERT_OPTIONS },
  { question: "My mood changes frequently throughout the day.",                   domain: "N", options: LIKERT_OPTIONS },
  { question: "I have frequent mood swings.",                                     domain: "N", options: LIKERT_OPTIONS },
  { question: "I get angry easily.",                                              domain: "N", options: LIKERT_OPTIONS },
  { question: "I often feel anxious before events.",                              domain: "N", options: LIKERT_OPTIONS },
  { question: "I get overwhelmed easily by everyday demands.",                    domain: "N", options: LIKERT_OPTIONS },
  { question: "I am not easily bothered by stressful situations.",               domain: "N", options: LIKERT_OPTIONS },
  { question: "I remain calm under pressure.",                                    domain: "N", options: LIKERT_OPTIONS },
  { question: "I handle difficult situations well.",                              domain: "N", options: LIKERT_OPTIONS },
  { question: "I seldom feel anxious or nervous.",                                domain: "N", options: LIKERT_OPTIONS },
  { question: "I am comfortable with uncertainty and change.",                    domain: "N", options: LIKERT_OPTIONS },
  { question: "I rarely let things get to me.",                                   domain: "N", options: LIKERT_OPTIONS },
  { question: "I feel secure and confident most of the time.",                    domain: "N", options: LIKERT_OPTIONS },
  { question: "I can bounce back quickly from setbacks.",                         domain: "N", options: LIKERT_OPTIONS },

  // ── Openness to Experience ────────────────────────────────────────────────
  { question: "I have a vivid imagination.",                                      domain: "O", options: LIKERT_OPTIONS },
  { question: "I enjoy thinking about abstract concepts and ideas.",              domain: "O", options: LIKERT_OPTIONS },
  { question: "I love hearing new and unconventional ideas.",                     domain: "O", options: LIKERT_OPTIONS },
  { question: "I enjoy exploring complex problems.",                              domain: "O", options: LIKERT_OPTIONS },
  { question: "I spend time reflecting on things.",                               domain: "O", options: LIKERT_OPTIONS },
  { question: "I am full of original ideas.",                                     domain: "O", options: LIKERT_OPTIONS },
  { question: "I am drawn to artistic or creative work.",                         domain: "O", options: LIKERT_OPTIONS },
  { question: "I love reading or researching topics on my own.",                  domain: "O", options: LIKERT_OPTIONS },
  { question: "I enjoy experiencing different cultures and ways of life.",        domain: "O", options: LIKERT_OPTIONS },
  { question: "I am curious about many different things.",                        domain: "O", options: LIKERT_OPTIONS },
  { question: "I prefer routine tasks over new and varied ones.",                 domain: "O", options: LIKERT_OPTIONS },
  { question: "I find abstract ideas hard to grasp.",                             domain: "O", options: LIKERT_OPTIONS },
  { question: "I avoid philosophical or deep discussions.",                       domain: "O", options: LIKERT_OPTIONS },
  { question: "I am not interested in art, music, or literature.",                domain: "O", options: LIKERT_OPTIONS },
  { question: "I prefer practical problems over theoretical ones.",               domain: "O", options: LIKERT_OPTIONS },
  { question: "I find it difficult to come up with original ideas.",              domain: "O", options: LIKERT_OPTIONS },
  { question: "I like to think about how things work in a big-picture way.",      domain: "O", options: LIKERT_OPTIONS },
  { question: "I am open to changing my beliefs when presented with new evidence.", domain: "O", options: LIKERT_OPTIONS },
];

export default questions;
